name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Login to AWS ECR
      run: |
        AWS_ACCOUNT_ID=125704090157
        AWS_ECR_REPO_NAME=app-telegram-bot
        APP_VERSION=$(grep -m 1 version pyproject.toml | grep -e '\d.\d.\d' -o)

        aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com

    - name: Build Docker image
      run: |
        AWS_ACCOUNT_ID=125704090157
        AWS_ECR_REPO_NAME=app-telegram-bot
        APP_VERSION=$(grep -m 1 version pyproject.toml | grep -e '\d.\d.\d' -o)

        IMAGE_NAME=$AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/$AWS_ECR_REPO_NAME:$APP_VERSION

        docker build -t $IMAGE_NAME .
        echo Build successful!

    - name: Push Docker image to AWS ECR
      run: |
        AWS_ACCOUNT_ID=125704090157
        AWS_ECR_REPO_NAME=app-telegram-bot
        APP_VERSION=$(grep -m 1 version pyproject.toml | grep -e '\d.\d.\d' -o)

        IMAGE_NAME=$AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/$AWS_ECR_REPO_NAME:$APP_VERSION

        docker push $IMAGE_NAME
